# Generated by Django 4.2.18 on 2025-02-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_dimage_image_alter_dimage_picture'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(to='portfolio.dimage'),
        ),
        migrations.AddField(
            model_name='tag',
            name='hex_color',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
