# Generated by Django 4.2.18 on 2025-02-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Post',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
