# Generated by Django 4.2.18 on 2025-01-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_live_example_project_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live_example',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
