# Generated by Django 4.2.18 on 2025-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_live_example_alter_project_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('role', models.TextField()),
                ('description', models.TextField()),
                ('resume', models.TextField()),
                ('contact', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
