# Generated by Django 4.2.18 on 2025-01-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_persone'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='github',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persone',
            name='linkedin',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
