# Generated by Django 4.2.18 on 2025-01-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_articale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(to='portfolio.dimage'),
        ),
    ]
