# Generated by Django 4.2.18 on 2025-01-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_dimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimage',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
