# Generated by Django 4.2.18 on 2025-01-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_dimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimage',
            name='image',
        ),
        migrations.AddField(
            model_name='dimage',
            name='picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
