# Generated by Django 4.2.18 on 2025-01-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_dimage_image_dimage_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimage',
            name='image',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dimage',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
