# Generated by Django 4.2.18 on 2025-02-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_dimage_image_alter_dimage_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
    ]
